--- 
- hosts: local
  become: yes
  tasks:
  - jenkins_job:
      config: "{{ lookup('template', 'template/test.xml.j2') }}"
      name: test
      token: 1153554321d29c021e79200b931a71272e
      url: http://3.18.102.54:8080
      user: project