---
- name: build job through ansible
  hosts: local
  become: yes
  vars:
    host: 3.18.102.54:8080
    job: ansible-job
    token: 1153554321d29c021e79200b931a71272e
    user: project
    password: project
  tasks:
  - name: jenkins
    uri:
      url: http://"{{ host }}"/job/"{{ job }}"/build?token="{{ token }}"
      user: "{{ user }}"
      password: "{{ password }}"
      method: GET
      force_basic_auth: yes
      status_code: 201